sudo: false
language: ruby
cache: bundler
rvm:
#- 2.1
- 2.1.1

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet --trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "dcP7eZWokuX8qoUg1WH0WTf2UNQmW7pYt0LSJq8Kpg9NC/vBPhsIwkauJs1H0fPStOImVO/LeZs04++pGqWeuuXtmriFf+6zMDyxzpaPZ3zDvFb7n70oaaFL2RBjnJAztHoshRBsTaVL6NIqucLkkAnV6YVS8qO3m3+eCMFSr5iHIrjPJX1PLvYlRuGtFXWl/myjEt6qeFf9wrlSmUupM8o57NEWmyIkUwEssEssFle1CYy1/0UpG6yxxPr5TzQCvkd9qCyfD6EOsb5dlB+ycyQWUzqU/1bINwBKNrP2xF/mDqR/AMjE59oGjQ2/KGgyAyy2OJL2iEM8ucJFK+KYtBBnduPTsuUbVjVCvIzTTL8TfkWivpTWE+BXr/u/hjCQpSOE+0HwRo9mt2AzgIj/x2qg5qL7J84PMtPiJ8bvFeHl5H2oPVzj1AGwLW/aRHEZVjTNcMhg9j4CCdV98epeTvc8mUsilXbyuZM77UAHIRnW91b8GC4cueyqcmtv13mcSq8NDEu6giSzA4hfkGRIe+R9IJ1AAComyZ0QX/n0SMa8NB3+phuomNi9a2q4abIRO146I+tiglxrwm7qI8ddzNczviK7odo0pOrVaOV7FD08rOrbL8/j3iF1FbRsX1p0mB9njDXaXEppvUdtt6R/yd4yG8+uhZA953WH8NFNYPI="
branches:
  only:
    - master

